### ISSUE TITLE
Unable to connect to host - api.developer.forge

### ISSUE THREAD

**Issue by saivaradula** [simonmoreau/RevitToIFC#1]
Hello Simon,
We have developed the same functionality as this project does with PHP as base technology. I did go well and was able to convert RVT file to IFC.  But from few days ( last 3 days ), We are not able to connect to the host or in other words not able to generate the token using the following service.

https://developer.api.autodesk.com/authentication/v1/authenticate with Secret Key and Client ID as post parameters. 

Can you suggest what went wrong with the service? 

I also observed that I am not able to upload or convert RVT file to IFC using your product.
URL:  https://revittoifc.bim42.com/home

Please let me know if you have any idea. 

- Sai

**Comment by simonmoreau** [comment]
Hello Sai,
I didin’t find any issue with RevitToIFC, maybe something was off for a short time.
I don’t know how to generate a Forge token with PHP, but you can have a look at the Azure C# function I use to get it : [https://github.com/simonmoreau/ForgeFunction](https://github.com/simonmoreau/ForgeFunction)
