### ISSUE TITLE
Cannot access through port 4200 after ng serve

### ISSUE THREAD

**Issue by iyotee** [simonmoreau/RevitToIFC#10]
Hi,

I git cloned and cd insite the folder.

Then i npm install and installed angular-cli parallely, 

then i ng serve from the RevitToIfc folder and all seems well webpacked and ask me to connect to localhost 4200. 

so i access my server from outside : 185.xxx.xxx.xxx:4200 and the connection is refused.

Please thanks to help me

**Comment by simonmoreau** [comment]
Hi,

If ng serve give you the following message :

`** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Compiled successfully.`

ererything should be fine. Just go to http://localhost:4200/  on your favorite browser and you should see Bimsync Manager running

Please let me know if it is working for you
