### ISSUE TITLE
Revit To IFC - ASP.NET C# sample source 

### ISSUE THREAD

**Issue by manikandan0598** [simonmoreau/RevitToIFC#11]
Hi,
We are trying to implement Revit to IFC Conversion in our ASP.NET C# Web application.
We need to integrate the Revit to IFC conversion in our web app.

Could you please provide the sample c# web application for RevitToIFC conversion.

Thank you in Advance and Wish you a very happy New Year!!!!

**Comment by simonmoreau** [comment]
Hi,

Sorry, but I only build an Angular version of this application. However, you can have a look at this Autodesk C# sample : [Desktop tool to manage buckets and objects](https://github.com/Autodesk-Forge/forge-bucketsmanager-desktop). You could also look into the [Forge .Net SDK](https://github.com/Autodesk-Forge/forge-api-dotnet-client).

Best,

Simon
