### ISSUE TITLE
Base Quantities - IFC exported file

### ISSUE THREAD

**Issue by saivaradula** [simonmoreau/RevitToIFC#2]
Hello Simon:

In Revit IFC export plugin, we have an option to check "base quantities" which extracts base quantities information from Revit and included into the exported IFC file. 

Is there any parameter that can be provided programmatically  while posting to Autodesk forge services so that we can get Base Quantities

- Sai

**Comment by simonmoreau** [comment]
There is no way for now to set up the IFC export settings, so the Forge conversion won’t work if you have specific requirements like BaseQuantities
