### ISSUE TITLE
Revit To IFC - Export schedules and base quantities

### ISSUE THREAD

**Issue by sureshbadra** [simonmoreau/RevitToIFC#4]
Hi Simon,

I'm able to manually export the following to ifc by ticking check
boxes (as shown in attached file) in revit desktop

1. Base quantities
2. Schedules as property sets 
3. Revit property sets

However revit to ifc is not exporting the following using forge web service:

1. Base quantities
2. Schedules as property sets 
3. Revit property sets

Pls modify revit2ifc forge web service to export Base Quantities, Schedules as property sets, Revit Property sets

or

alternatively pls suggest ways to read Base Quantities, Schedules as property sets, Revit Property sets
using forge api such as model derivative api
 
Thanks
Suresh Badra

![revit_ifc_properties](https://user-images.githubusercontent.com/33412818/41451645-91132f6e-708b-11e8-9011-730ae4be245a.jpg)

**Comment by simonmoreau** [comment]
I am sorry,but at the moment, there is no way to set up the IFC export settings, so the Forge conversion won’t work if you have specific requirements like BaseQuantities

**Comment by sureshbadra** [comment]
Does forge model derivatives api reads the following?
1. Base Quantities
2. Schedules as property sets
3. Revit Property sets
Thanks.
Suresh Badra
