### ISSUE TITLE
Base Quantities and Schedules - Revit to IFC

### ISSUE THREAD

**Issue by sureshbadra** [simonmoreau/RevitToIFC#5]
Hi Simon,

Thanks for the quick reply.
One more question, can we convert revit to ifc using forge model derivatives api?
Does forge model derivatives api reads to the following:
1. Base Quantities
2. Schedules as property sets
3. Revit Property sets

Thanks.
Suresh Badra

**Comment by simonmoreau** [comment]
I am actually using the Forge Model Derivatives API to power RevitToIFC. I didn't found any way to edit the IFC conversion settings, so I don't see any way of exporting BaseQuantities or specific property sets.
