### ISSUE TITLE
How to show dimensions created in revit 3d model in bim360 web viewer?

### ISSUE THREAD

**Issue by sureshbadra** [simonmoreau/RevitToIFC#6]
Hi Simon,
 
I would like know if bim360 supports the following:
 
1. Provision to export dimensions/annotations from revit desktop 3d model to ifc through api
2. Display dimensions/annotations in 3d in forge web viewer similar to dimensions shown in attached file
 
![desktop revit3d model with dimensions](https://user-images.githubusercontent.com/33412818/41703386-ba352798-7550-11e8-8c4b-585b4ad7c688.png)

Any suggestions/references will be a help.
 
Thanks
Suresh

**Comment by simonmoreau** [comment]
1. IFC doesn't support annotations, so I don't think we can export these dimensions to IFC
2. I don't know if the Forge Web viewer support can retrieve these dimension
